name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm install
        npm ci
        npm test
        git config --global user.email "bot@github.com"
        git config --global user.name "BOT SHARK"
        git add .
        git commit -m "Add DIST"
        git push origin master
      env:
        CI: true
