name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        files: [dist,src]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm install
        npm ci
        npm test
      env:
        CI: true
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
         name: packedfiles-${{matrix.files}}
         path: ./${{matrix.files}}    
