name: WebPack

on: [push]

jobs:
 Webpack:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        files: [dist,src]

    steps:
    - uses: actions/checkout@v1
    - name: Cache
      uses: actions/cache@v1.0.3
      with:
         path: node_modules
         key:  news
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build
      run: |
        npm install
        npm ci
        npm test
      env:
        CI: true
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
         name: packedfiles-${{matrix.files}}
         path: ./${{matrix.files}}
